[project]
name = "enjambre-agentes"
version = "0.1.0"
description = "Enjambre de Agentes para Recolección Ecológica y Agrícola de México"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-google-genai",
    "langchain-text-splitters",
    "langchain-experimental",
    "langchain-huggingface",
    "langchain-groq>=0.1.5",
    "langchain-cohere>=0.1.7",
    "langgraph",
    "INEGIpy>=1.1.2",
    "google-generativeai",
    "faiss-cpu",
    "tavily-python",
    "groq",
    "cohere",
    "playwright",
    "beautifulsoup4",
    "lxml",
    "pypdf",
    "python-dotenv",
    "pydantic",
    "requests",
    "aiohttp",
    "aiofiles"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv]
managed = true
