[project]
name = "enjambre-agentes"
version = "0.1.0"
description = "Sistema de Apoyo Multiagente para el Manejo Agrícola y Preservación de Polinizadores (AgriPoli)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # Ecosistema LangChain
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-google-genai",
    "langchain-text-splitters",
    "langchain-experimental",
    "langchain-huggingface",
    "langchain-ollama",
    "langchain-pinecone",
    "langchain-groq>=0.1.5",
    "langchain-cohere>=0.1.7",
    "langchain-tavily",
    "langchain-chroma>=1.1.0",
    
    # LangGraph
    "langgraph",
    
    # Proveedores e IA
    "google-generativeai",
    "faiss-cpu",
    "torch",
    "torchvision",
    "transformers",
    "huggingface-hub",
    "ollama",
    "sentence-transformers",
    "tavily-python",
    "groq",
    "cohere",
    "chromadb>=1.5.9",
    "pinecone",
    
    # Web Scraping y Procesamiento
    "pypdf",
    "pymupdf",
    "beautifulsoup4",
    "bs4",
    "unstructured",
    "unstructured-client",
    "lxml",
    "arxiv",
    "wikipedia",
    "selenium",
    "webdriver-manager",
    "playwright",
    
    # Matemáticas
    "sympy",
    "numpy",
    "pandas",
    
    # Utilidades y Entorno
    "python-dotenv",
    "ipython",
    "requests",
    "aiohttp",
    "aiofiles",
    "pydantic",
    
    # Propios del Proyecto
    "INEGIpy>=1.1.2"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv]
managed = true
